language: clojure
lein: lein
script: lein sub install; LEIN_CMD=lein lein sub test :travis
branches:
  only:
    - master
jdk:
  - oraclejdk8
notifications:
  email:
    - pedestal@thinkrelevance.com
